table o_log_desenvolvimento
	lineageTag: 352272ad-2636-4905-a09d-59923cab185e

	column Observacao
		dataType: string
		lineageTag: 13dc6976-26ff-47ff-8099-a500d91fe28f
		summarizeBy: none
		sourceColumn: Observacao

		annotation SummarizationSetBy = Automatic

	column 'Total de Minutos'
		dataType: double
		formatString: #,0
		lineageTag: e95343bb-27bd-496e-b629-a5947708a6b1
		summarizeBy: sum
		sourceColumn: Total de Minutos

		annotation SummarizationSetBy = Automatic

	column dt_inicio
		dataType: dateTime
		formatString: Short Date
		lineageTag: ef36019a-6b03-4f61-86f6-96f8e15e8711
		summarizeBy: none
		sourceColumn: dt_inicio

		annotation SummarizationSetBy = Automatic

	column dt_fim
		dataType: dateTime
		formatString: Short Date
		lineageTag: cc90921d-a780-4f24-a7a7-6abf01c4b4be
		summarizeBy: none
		sourceColumn: dt_fim

		annotation SummarizationSetBy = Automatic

	partition o_log_desenvolvimento = m
		mode: import
		source = ```
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("rZNba9tAEIX/yqKnFFx0s4ntt/SSNg8lbpLSh2DKSBonQ1c77e7Kof31nV3JthwMhTZgtIOs+fbsmbP390kxT/MsLbJimkySfLrMMvmF8nxZDuUnblDDA7aqYacaCM+aW7XiJ7SfO7S/kvXkOenQns/35criD7BQAwtKQVsRGo8qvFMP5NUZG00GJ/LGeXBK/jrqMOyxYv7ed3gLFehHsFGN9L/qdSxGOrL5/kTZYl+uLLVIlkNjSz62ldlfjTgcWL1Wby31slAoujNRbiNc4xhdr3ADNWnyohBUvftePmyxIVlP7HvQWOQjuSdte+QWebOhenCwZuPJdLIb77xhJVOrwYE6IyOW6h3kK5mGn1y6enOVXkdGeuE70PQbapHfO5nlaZ4fSQu6yuUsrDfoWG9RMDIkrjS2oIwcuTODKx+vby5uv325e39129OKES3OJVCLfv0/Wj4baIuXoEXnh5Mu/olWjrXtclRKjmR9hw7NVoAhKj4OY0tOrJdMXZL2lt1E3UElV06KDxZkOByyddmJghP82bHal+BPx/zzXne8xs/D6BTYnx1teQi87EySULlYOmY0Wa//AA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Data = _t, Inicio = _t, Fim = _t, Observacao = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Data", type date}, {"Inicio", type time}, {"Fim", type time}}),
				    
				    #"Coluna Mesclada Inserida" = Table.AddColumn(
				        #"Tipo Alterado",
				        "dt_inicio",
				        each 
				            Text.Combine(
				                {
				                    Text.From([Data], "pt-BR"), 
				                    Text.From([Inicio], "pt-BR")
				                }, 
				                " "
				            ), 
				        type datetime
				    ),
				    #"Personalização Adicionada" = Table.AddColumn(#"Coluna Mesclada Inserida", "Personalizar", each ([Fim] - [Inicio]), type time),
				    #"Minutos Totais Inseridos" = Table.AddColumn(#"Personalização Adicionada", "Total de Minutos", each Duration.TotalMinutes([Personalizar]), type number),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Minutos Totais Inseridos",{"Personalizar"}),
				    #"Coluna Mesclada Inserida1" = Table.AddColumn(#"Colunas Removidas", "dt_fim", each Text.Combine({Text.From([Data], "pt-BR"), Text.From([Fim], "pt-BR")}, " "), type datetime),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Mesclada Inserida1",{{"dt_inicio", type datetime}, {"dt_fim", type datetime}}),
				    
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Tipo Alterado1",{"Data", "Inicio", "Fim"})
				in
				    #"Colunas Removidas1"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

