table o_log_desenvolvimento
	lineageTag: 352272ad-2636-4905-a09d-59923cab185e

	column Observacao
		dataType: string
		lineageTag: 13dc6976-26ff-47ff-8099-a500d91fe28f
		summarizeBy: none
		sourceColumn: Observacao

		annotation SummarizationSetBy = Automatic

	column 'Total de Minutos'
		dataType: double
		lineageTag: e95343bb-27bd-496e-b629-a5947708a6b1
		summarizeBy: sum
		sourceColumn: Total de Minutos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dt_inicio
		dataType: dateTime
		formatString: General Date
		lineageTag: ef36019a-6b03-4f61-86f6-96f8e15e8711
		summarizeBy: none
		sourceColumn: dt_inicio

		annotation SummarizationSetBy = Automatic

	column dt_fim
		dataType: dateTime
		formatString: General Date
		lineageTag: cc90921d-a780-4f24-a7a7-6abf01c4b4be
		summarizeBy: none
		sourceColumn: dt_fim

		annotation SummarizationSetBy = Automatic

	column saldo_segundos
		dataType: double
		lineageTag: 85233147-b042-4c1a-ab21-3794e4394a2e
		summarizeBy: sum
		sourceColumn: saldo_segundos

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition o_log_desenvolvimento = m
		mode: import
		source = ```
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("lZFfS8MwFMW/SuiTwqRpN3Hb2xTBPcjqpvgwhty2d1swyZUkdein97bdXxmIUHIvac7J757M51HajxMZpzLtRZ0o6Q2l5K9ub4bdbftIJWpYoREleVFCvRZkREYbdE8Vuq9o0fntdJAn/X2bOfwABwUQWwkwuUIbUNR7YqWCuCCrlcUO7/gAXvCvE4WlgDnRe6sIDnLQa3ANDesvW47BEYfs7yeSg32bOWVQOaqFRoVG1pV/BnEYWFyJO6daLGQXXdkGt2Rf6wl9S7iEQmkVmBBEsTvPBw2WiuuZew+MaXKEeza2NRmk5VIV2wQLskHZim+jXTYk+NUK8CAulOVI9c7kVdmSNj7ObsfxpPGIR6ECrb6hYPw2SZnESXKCVnN1h9d1naIn/Ylsw49EuUYDwvLIld2m8jCZjmZvL8/341nrlh65Ne9Su6Zt/Z/b4gc=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Data = _t, Inicio = _t, Fim = _t, Observacao = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Data", type date}, {"Inicio", type time}, {"Fim", type time}}),
				    
				    #"Coluna Mesclada Inserida" = Table.AddColumn(
				        #"Tipo Alterado",
				        "dt_inicio",
				        each 
				            Text.Combine(
				                {
				                    Text.From([Data], "pt-BR"), 
				                    Text.From([Inicio], "pt-BR")
				                }, 
				                " "
				            ), 
				        type datetime
				    ),
				    #"Personalização Adicionada" = Table.AddColumn(#"Coluna Mesclada Inserida", "Personalizar", each ([Fim] - [Inicio]), type time),
				    #"Minutos Totais Inseridos" = Table.AddColumn(#"Personalização Adicionada", "Total de Minutos", each Duration.TotalMinutes([Personalizar]), type number),
				    #"Colunas Removidas" = Table.RemoveColumns(#"Minutos Totais Inseridos",{"Personalizar"}),
				    #"Coluna Mesclada Inserida1" = Table.AddColumn(#"Colunas Removidas", "dt_fim", each Text.Combine({Text.From([Data], "pt-BR"), Text.From([Fim], "pt-BR")}, " "), type datetime),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Coluna Mesclada Inserida1",{{"dt_inicio", type datetime}, {"dt_fim", type datetime}}),
				    
				    // obter as horas uteis trabalhadas
				    #"Função Personalizada Invocada" = Table.AddColumn(
				        #"Tipo Alterado1",
				        "saldo_segundos", each fx_horas_uteis(
				            #time(8, 0, 0),
				            #time(18, 0, 0),
				            [dt_inicio],
				            [dt_fim],
				            d_feriados_anbima[Data]
				        )
				    ),
				    
				    #"Colunas Removidas1" = Table.RemoveColumns(#"Função Personalizada Invocada",{"Data", "Inicio", "Fim"}),
				    #"Tipo Alterado2" = Table.TransformColumnTypes(#"Colunas Removidas1",{{"saldo_segundos", type number}})
				in
				    #"Tipo Alterado2"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

